### ISSUE TITLE
install以后会出现问题

### ISSUE THREAD

**Issue by Wentao0909** [javaLuo/vue-puzzle-vcode#22]
Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by javaLuo** [comment]
1.0.6版本解决了因vue版本不一致导致的报错问题
试试呢
