### ISSUE TITLE
Vue3.2.8用不了

### ISSUE THREAD

**Issue by Alice-Rozalia** [javaLuo/vue-puzzle-vcode#23]
在vue3.2.8的script-setup写法下，拼图绘制区域一片白，滑块和刷新无效

**Comment by javaLuo** [comment]
是最新版本吗，之前修复过，是因为3.2.20以下的版本vue不允许没有使用的ref。
如果可以的话，vue升级到3.2.20以上试试

**Comment by Alice-Rozalia** [comment]
> 是最新版本吗，之前修复过，是因为3.2.20以下的版本vue不允许没有使用的ref。 如果可以的话，vue升级到3.2.20以上试试

已升级版本解决，感谢作者
