### ISSUE TITLE
vue3 报错 图片显示不出来 无法拖动

### ISSUE THREAD

**Issue by lixinliA** [javaLuo/vue-puzzle-vcode#27]
![image](https://user-images.githubusercontent.com/20835672/157170924-e348b4df-a72e-47b4-9319-de098f6e22cf.png)

**Comment by javaLuo** [comment]
升级一下vue呢，升到vue3.2.x试试

**Comment by javaLuo** [comment]
我这没问题额
你是用的webpack还是vite打包的
把node_modules删除重新install试试呢

**Comment by yundou147** [comment]
![image](https://user-images.githubusercontent.com/73925530/165755585-747edfb5-b286-4988-96cc-732c80f65b5f.png)
我这里也是用的vite打包 vue3.2

**Comment by javaLuo** [comment]
我用vite试了一下，没发现有问题。
如果实在不行，试试直接将源代码复制进项目
https://github.com/javaLuo/vue-puzzle-vcode/tree/vue3
这个地址的src目录就是这个组件的源代码，就是一个普通vue组件，直接用就行。

**Comment by javaLuo** [comment]
我发布了1.0.6，试试还会有问题吗
这可能是因为npm上传时带入了不同版本vue导致的
