### ISSUE TITLE
组件在火狐浏览器有bug

### ISSUE THREAD

**Issue by wkjjkw** [javaLuo/vue-puzzle-vcode#3]
火狐浏览器下用来填充的小图有背景。

**Comment by javaLuo** [comment]
ok ,我来搞定

**Comment by javaLuo** [comment]
hi，貌似我没发现问题额。
如果你说的是拼图缺失的那一块地方有隐隐约约的图案的话，那里是故意的，用了一点透明度

**Comment by wkjjkw** [comment]
![tim 20190222185407](https://user-images.githubusercontent.com/26787245/53238046-3f544f00-36d3-11e9-976e-026840b99040.png)

**Comment by wkjjkw** [comment]
火狐版本是65.0.1

**Comment by javaLuo** [comment]
OK, 我看到了，我来处理

**Comment by javaLuo** [comment]
hi，我更新了1.0.4，搞好了。

**问题的原因：**
windows下Firefox的canvas中如果先设置了`ctx.shadowBlur`绘制外阴影，再`ctx.drawImage()`绘制图片，此时绘制的图片会无视`ctx.clip()`裁剪区域<br/>
我猜这是windows版Firefox的BUG，因为MAC的Firefox正常。

感谢指出问题,3Q

**Comment by wkjjkw** [comment]
好的，解决了。另外提一下，ie浏览器未实现includes方法，如果有兼容ie的需求，建议使用此组件前务必安装babel。

**Comment by wkjjkw** [comment]
为了减少打包体积，我没有安装babel，只加了相应的polyfill

**Comment by javaLuo** [comment]
貌似你之前还说了个 IE不支持includes来着
我明天还是改成indexOf吧..
