### ISSUE TITLE
和vue antd 结合登录使用 IE浏览器不出现

### ISSUE THREAD

**Issue by zhulaokai111** [javaLuo/vue-puzzle-vcode#4]
打开登录页，页面一直加载中，注掉滑动验证就正常了

**Comment by javaLuo** [comment]
建议直接把src/app.vue这个文件复制到你的项目里，换个名字，就是一个普通组件，直接用。
我这个发布到npm没有加babel-polyfill,所以在IE中要报错。(加babl-polyfill体积太大了)

**Comment by zhulaokai111** [comment]
> 建议直接把以下文件复制到你的项目里，换个名字，就是一个普通组件，直接用。
> 
> ```js
> src/app.vue // 这就是个普通的vue组件
> src/assets // 这个里面有两张小图片，是app.vue要用的
> ```
> 
> 我这个发布到npm没有加babel-polyfill,所以在IE中要报错。(加babl-polyfill体积太大了)

**Comment by zhulaokai111** [comment]
感谢作者，成功解决了
