### ISSUE TITLE
不能将类型“{ show: boolean; }”分配给类型“ComponentProps<number>”。   不能将类型“{ show: boolean; }”分配给类型“number”。ts(2322)

### ISSUE THREAD

**Issue by JCAlways** [javaLuo/vue-puzzle-vcode#40]
不能将类型“{ show: boolean; }”分配给类型“ComponentProps<number>”。
  不能将类型“{ show: boolean; }”分配给类型“number”。ts(2322)

**Comment by javaLuo** [comment]
```
<Vcode :show="true" />
```
是这样吗

**Comment by reaishenghuodezhu** [comment]
`<script lang="ts" setup>`
这里指定ts后会报
![image](https://user-images.githubusercontent.com/93962740/214836319-4c2fb356-bba9-4465-9298-45430344a7b8.png)

**Comment by javaLuo** [comment]
我看看

**Comment by JCAlways** [comment]
![image](https://user-images.githubusercontent.com/40380551/219990550-caf09f3f-084b-4dbf-842b-db835fcb8a9b.png)
![image](https://user-images.githubusercontent.com/40380551/219990562-fc66d2e6-7322-4e7a-9584-7d3b97403b47.png)
![image](https://user-images.githubusercontent.com/40380551/219990625-89fdee9d-7148-41d7-83e6-ad3c3aa7ebf0.png)
可能是这边名命的问题

**Comment by javaLuo** [comment]
我已经把名称改了
TS问题
