### ISSUE TITLE
运行webpack直接报错

### ISSUE THREAD

**Issue by kanglinghui** [javaLuo/vue-puzzle-vcode#45]
![image](https://user-images.githubusercontent.com/38158988/225571406-4aa78c21-e6ed-49f7-a6fc-aaba67a3a37c.png)

**Comment by kong7788** [comment]
+1

**Comment by javaLuo** [comment]
我回去看看

**Comment by javaLuo** [comment]
现在应该不会了
改了一下TS命名

**Comment by kong7788** [comment]
刚刚是了一下，还是不行，一样的报错，vue3 + ts

**Comment by kong7788** [comment]
![WX20230322-214816@2x](https://user-images.githubusercontent.com/22022552/226924954-7c64d435-0ea1-43fd-aa25-495fc14d2625.png)
