### ISSUE TITLE
nuxt3打包报错

### ISSUE THREAD

**Issue by WilliamAdolph** [javaLuo/vue-puzzle-vcode#47]
![image](https://github.com/javaLuo/vue-puzzle-vcode/assets/36332969/221f5c32-5dd1-4a95-83a3-325644a19ad0)
这个想问下可以用在nuxt3吗，我安装后可以使用，但是build时候有这个错误

**Comment by javaLuo** [comment]
我试试

**Comment by javaLuo** [comment]
这个组件，用vite打包编译的，会生成一个css
我把这个css自动import到生成的js里了，这样不用引用组件时还要手动引用css,
但nuxt3打包时似乎无法识别css相对路径，
我没找到好的解决办法。我不想把css又和js混在一起。
我再想想怎么弄

**Comment by javaLuo** [comment]
Hi, 请使用这个版本：
`npm install vue3-puzzle-vcode@1.0.15-nuxt`;

由于Nuxt3打包服务端代码用了Nitro, 这个工具打包的时候不知道为什么无法识别相对路径引用的CSS。
所以我做了一个特殊版本`1.0.15-nuxt`,
以后的每次发布新版本，我都会同时发布一个兼容nuxt3的版本
