### ISSUE TITLE
只能是模态框的形式吗，想让其出现在指定div内应该如何操作

### ISSUE THREAD

**Issue by 123liuyu123** [javaLuo/vue-puzzle-vcode#50]
谢谢

**Comment by wtt2015** [comment]
同问

**Comment by javaLuo** [comment]
我想想办法

**Comment by javaLuo** [comment]
我发布了1.1.3
`<Vcode type="inside" />`, 像这样调整为内嵌模式。
这样的话你需要自己定义外部容器的大小和样式了。
DEMO: https://isluo.com/work/vue-puzzle-vcode/
